repositories:
  - name: "bianca"
    type: "deb"  # Repository type: rpm or deb
    # baseURL: "https://mirror.elxr.dev/elxr/dists/aria/main"
    baseURL: "https://mirror.elxr.dev/elxr"
    pkgPrefix: "https://mirror.elxr.dev/elxr/"
    releaseFile: "https://mirror.elxr.dev/elxr/dists/bianca/Release"
    releaseSign: "https://mirror.elxr.dev/elxr/dists/bianca/Release.gpg"
    pbGPGKey: "https://mirror.elxr.dev/elxr/public.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main"  # Repository component/section identifier
    buildPath: "./builds/elxr12/main"  # Will be replaced with temp_dir/builds/elxr12 at runtime
  - name: "bianca-security"
    type: "deb"  # Repository type: rpm or deb
    # baseURL: "https://mirror.elxr.dev/elxr/dists/aria/main"
    baseURL: "https://mirror.elxr.dev/elxr"
    pkgPrefix: "https://mirror.elxr.dev/elxr/"
    releaseFile: "https://mirror.elxr.dev/elxr/dists/bianca-security/Release"
    releaseSign: "https://mirror.elxr.dev/elxr/dists/bianca/Release.gpg"
    pbGPGKey: "https://mirror.elxr.dev/elxr/public.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main"  # Repository component/section identifier
    buildPath: "./builds/elxr12/security"  # Will be replaced with temp_dir/builds/elxr12 at runtime
  - name: "bianca-updates"
    type: "deb"  # Repository type: rpm or deb
    # baseURL: "https://mirror.elxr.dev/elxr/dists/aria/main"
    baseURL: "https://mirror.elxr.dev/elxr"
    pkgPrefix: "https://mirror.elxr.dev/elxr/"
    releaseFile: "https://mirror.elxr.dev/elxr/dists/bianca-updates/Release"
    releaseSign: "https://mirror.elxr.dev/elxr/dists/bianca-updates/Release.gpg"
    pbGPGKey: "https://mirror.elxr.dev/elxr/public.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main"  # Repository component/section identifier
    buildPath: "./builds/elxr12/updates"  # Will be replaced with temp_dir/builds/elxr12 at runtime
  - name: "bookworm"
    type: "deb"
    baseURL: "https://deb.debian.org/debian"
    pkgPrefix: "https://deb.debian.org/debian/"
    releaseFile: "https://deb.debian.org/debian/dists/bookworm/Release"
    releaseSign: "https://deb.debian.org/debian/dists/bookworm/Release.gpg"
    pbGPGKey: "https://ftp-master.debian.org/keys/archive-key-12.asc"  # Debian 12 key
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main"
    buildPath: "./builds/debian/bookworm"
